SELECT * FROM CADFUN;
--O * SIGNIFICA QUE É PARA SELECIONAR TODAS AS COLUNAS.

SELECT NOME, SALARIO FROM CADFUN;
-- AQUI NÃO TEM O "*" POIS TEM MAIS DE UMA TABELA.

SELECT NOME, SALARIO,FUNCAO FROM CADFUN;
-- AQUI É O MESMO EXEMPLO DO DE CIMA, MAS COM  MAIS INFORMAÇÕES

SELECT * FROM CLIENTE;

SELECT NOME, CIDADE FROM CLIENTE;

SELECT NOME, CIDADE FROM CLIENTE ORDER BY NOME;
-- SELECIONOU O NOME E CIDADE PELO NOME POR CONTA DO "ORDER BY"

SELECT NOME, CIDADE FROM CLIENTE ORDER BY CIDADE;
-- AQUI EI SELECIONEI OS NOME DA CIDADE EM ORDEM

SELECT CIDADE, NOME FROM CLIENTE ORDER BY CIDADE, NOME;

SELECT CIDADE, NOME FROM CLIENTE ORDER BY CIDADE, NOME DESC;
-- O DESC DEIXA EM ORDEM DECRESCENTE, O ASC DEIXA EM CRESCENTE

SELECT * FROM VENDA ORDER BY VENCTO;

SELECT * FROM CADFUN ORDER BY FUNCAO;

SELECT * FROM CADFUN WHERE FUNCAO = 'SECRETARIA' ORDER BY NOME;
-- NESSE COD É PARA FILTTRAR NA TABBELA APENAS AS SECRETARIA, COMO NO EX AI, EM NOME DE ORDEM

SELECT * FROM CADFUN WHERE DEPTO = '3';
-- AQUI EU SELECIONEI TODOS DO CADFUN, COM O DEPTO 3

SELECT * FROM CADFUN WHERE DEPTO = '3' AND FILHOS = 1;

SELECT NOME, FUNCAO FROM CADFUN;

SELECT CODFUN, NOME, FUNCAO FROM CADFUN;

SELECT CODFUN, NOME, FUNCAO, DEPTO FROM CADFUN;

SELECT NOME FROM CADFUN WHERE DEPTO = '5';

SELECT NOME, DEPTO FROM CADFUN WHERE FUNCAO = 'VENDEDOR';

SELECT SALARIO FROM CADFUN WHERE DEPTO = '3';

SELECT FUNCAO, NOME FROM CADFUN ORDER BY FUNCAO DESC;

SELECT FUNCAO, NOME FROM CADFUN ORDER BY FUNCAO DESC, NOME ASC;

SELECT * FROM CADFUN WHERE NOME LIKE '%E%';

SELECT NOME, DEPTO FROM CADFUN WHERE FUNCAO = 'ANALISTA' AND SALARIO > 1200;